---
default:
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  adapter: postgresql
  database: chezjocay_development
  encoding: unicode
  pool: 5
production:
  adapter: postgresql
  database: chezjocay_production
  encoding: unicode
  password: "<%= ENV['CHEZJOCAY_DATABASE_PASSWORD'] %>"
  pool: 5
  username: chezjocay
test:
  adapter: postgresql
  database: chezjocay_test
  encoding: unicode
  pool: 5
