# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a62010aaa548b2d76857b74432783e0e4c442c89eb9d6925d1433fb3594edc10cd09fc31bec319febdf6af27a4590fd78f9b2b0c6496dc5a0736f19f5e301a3

test:
  secret_key_base: 248e4b4175da17f0034ed38afe432c8750f7f81ea91b8e15176a0b24383f063462e32b88a38e4d46ec68336d02c9fa565148fbee71aa58199d05812920b9ca31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
